
[LeMonde]
name = "LeMonde"
feeds = [
    ["Politique", "https://www.lemonde.fr/politique/rss_full.xml"],
    ["Une", "https://www.lemonde.fr/rss/une.xml"],
    ["Idées","https://www.lemonde.fr/idees/rss_full.xml"]]

[Liberation]
name = "Libération"
feeds = [
    ["all","https://www.liberation.fr/arc/outboundfeeds/rss-all/?outputType=xml"]]

[SZ]
name="SZ"
feeds=[["TopThemen", "https://rss.sueddeutsche.de/rss/Topthemen"]]

[Corriere]
name="Corriere"
feeds=[["all", "http://xml2.corriereobjects.it/rss/homepage.xml"]]

[Zeit]
name="Zeit"
feeds=[["Zeit - all", "https://newsfeed.zeit.de/index"]]

[Handelsblatt]
name="Handelsblatt"
feeds=[["Handelsblatt - all", "https://www.handelsblatt.com/contentexport/feed/top-themen"]]

[FAZ]
name="FAZ"
feeds=[["FAZ - all", "https://faz.net/rss/aktuel"]]

[Echos]
    name="LesEchos"
    feeds=[
        ["Echos - Idées", "https://services.lesechos.fr/rss/les-echos-idees.xml"],
        ["Echos - Economie", "https://services.lesechos.fr/rss/les-echos-economie.xml"],
        ["Echos - Finance/Marchés", "https://services.lesechos.fr/rss/les-echos-finance-marches.xml"]
    ]

