[project]
name = "actur"
version = "0.1.0"
description = "news reader using RSS feeds"
readme = "README.rst"
license = "MIT"
authors = [
    {name = "Art Goldhammer", email = "art.goldhammer@gmail.com"},
]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "beautifulsoup4==4.12.3",
    "click==8.1.7",
    "colorama==0.4.6",
    "feedparser==6.0.11",
    "openai==1.43.0",
    "pendulum==3.0.0",
    "pymongo==4.8.0",
]

[project.urls]
Homepage = "https://github.com/agoldhammer/actur"

[project.scripts]
actu = "actur.actu_cli:cli"
readnews = "actur.reader:main"
tryout = "actur.tryout:main"

[dependency-groups]
dev = [
    "black==24.8.0",
    "bump2version==1.0.1",
    "coverage==7.6.1",
    "pytest==8.3.2",
    "sphinx==8.0.2",
    "time-machine==2.15.0",
    "tox==4.18.0",
    "twine==5.1.1",
    "watchdog==5.0.2",
    "wheel==0.44.0",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["actur", "actur.*"]
